all: xseq

GCC=g++

VERSION_MAJOR=1
VERSION_MINOR=0
VERSION_SUB_MINOR=1
VERSION_DEFINES=-DVERSION_MAJOR=$(VERSION_MAJOR) -DVERSION_MINOR=$(VERSION_MINOR) -DVERSION_SUB_MINOR=$(VERSION_SUB_MINOR)
FLAGS=-Werror -Wall -O3
LIBS=
STATIC_LIBS=
BUILD_DIR=build
DEBUG_FLAGS=-DDEBUG_PROGRAM_OPTIONS="1"
RELEASE_FLAGS=

clean:
	rm build/*

build-dir:
	mkdir -p $(BUILD_DIR)

xseq: build-dir
	$(GCC) $(FLAGS) $(RELEASE_FLAGS) $(INCLUDES) \
		./src/main.cpp -o $(BUILD_DIR)/xseq $(STATIC_LIBS) $(LIBS)

test-xseq: build-dir
	$(GCC) $(FLAGS) $(DEBUG_FLAGS) $(INCLUDES) \
		./src/main.cpp -o $(BUILD_DIR)/xseq $(STATIC_LIBS) $(LIBS)
